zz <- file(paste(spec, "modelParameterSummary.txt", sep = ''), "w")  
cat('Species = ', spec , file = zz,  "\n")
cat('Make Init file used = ', minit.file, file = zz,  "\n")
cat('# Bootstrap Iterations = ', nboot, file = zz,  "\n")
cat('Demographic Stochasticity Threshold = ', threshold, file = zz, "\n")
cat('Population size = ', pmean, file = zz, "\n")
cat('Calf/pup survival = ', Surv[1], file = zz, "\n")
cat('Juvenile survival = ', Surv[7], file = zz, "\n")
cat('Adult survival = ', Surv[13], file = zz, "\n")
cat('Fecundity value = ', Fertility, file = zz, "\n")
cat('Age at which a calf or pup becomes independent of its mother = ', age1, file = zz, "\n")
cat('Age at which an average female gives birth to her first calf = ', age2, file = zz, "\n")
cat('Proportion of animals in each of the vulnerable sub-population(s), default is that the entire population is vulnerable = ', vulnmean, file = zz, "\n")
cat('Number of years on which piling will occur = ', pile_years, file = zz, "\n")
cat('Name of csv file that contains information on days on which piling will occur = ', piling.file, file = zz, "\n")
cat('Number of piling operations to be modelled = ', pilesx1, file = zz, "\n")
cat('Which operations will affect each vulnerable sub-population = ', vulnpile[1, ], file = zz, "\n")
cat('Number of seasons = ', seasons, file = zz, "\n")
cat('Number of animals predicted to experience significant disturbance on one day of piling for each operation = ', numDT, file = zz, "\n")
cat('Number of animals predicted to experience PTS on one day of piling = ', numPT, file = zz, "\n")
cat('Number of days of "residual" disturbance = ', days, file = zz, "\n")
cat('Can PTS occur on any day = ', Day1, file = zz, "\n")
close(zz)
